kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/dsbrng25b/mip

steps:
- name: build
  image: golang
  commands:
  - curl --fail -L -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 && chmod +x /usr/local/bin/dep
  - dep ensure
  - make
- name: release tag
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    file:
    - mip
    - mip-win64.exe
    checksum:
    - sha256
  when:
    event:
    - tag
