project_name: mip
builds:
- goos:
  - linux
  - windows
  goarch:
  - amd64
  main: ./cmd/mip
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: mip
archive:
  format: zip
  replacements:
    amd64: 64bit
    windows: win
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
